[2024-10-26T07:16:59.138+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:16:59.225+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_dim_dates scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-10-26T07:16:59.249+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_dim_dates scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-10-26T07:16:59.260+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-26T07:16:59.330+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_dim_dates> on 2024-01-02 00:00:00+00:00
[2024-10-26T07:16:59.349+0000] {standard_task_runner.py:63} INFO - Started process 280 to run task
[2024-10-26T07:16:59.356+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform_dim_dates', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpc59xq206']
[2024-10-26T07:16:59.366+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask transform_dim_dates
[2024-10-26T07:16:59.563+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform_dim_dates scheduled__2024-01-02T00:00:00+00:00 [running]> on host eed3011aebc3
[2024-10-26T07:16:59.946+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform_dim_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-10-26T07:16:59.952+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:17:00.012+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:17:00.016+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform_dim_dates.py", line 5, in transform_dim_dates
    warehouse_operator = PostgresOperator('postgres_warehouse')
NameError: name 'PostgresOperator' is not defined
[2024-10-26T07:17:00.057+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=e_commerce_dw_etl, task_id=transform_dim_dates, run_id=scheduled__2024-01-02T00:00:00+00:00, execution_date=20240102T000000, start_date=20241026T071659, end_date=20241026T071700
[2024-10-26T07:17:00.103+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task transform_dim_dates (name 'PostgresOperator' is not defined; 280)
[2024-10-26T07:17:00.158+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-26T07:17:00.225+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T07:17:00.231+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
