[2024-10-26T07:16:56.114+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:16:56.212+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_dim_dates scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-10-26T07:16:56.244+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_dim_dates scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-10-26T07:16:56.245+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-26T07:16:56.274+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_dim_dates> on 2024-01-01 00:00:00+00:00
[2024-10-26T07:16:56.288+0000] {standard_task_runner.py:63} INFO - Started process 249 to run task
[2024-10-26T07:16:56.309+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform_dim_dates', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpw1e1uiqa']
[2024-10-26T07:16:56.323+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask transform_dim_dates
[2024-10-26T07:16:56.901+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform_dim_dates scheduled__2024-01-01T00:00:00+00:00 [running]> on host eed3011aebc3
[2024-10-26T07:16:57.756+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform_dim_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-10-26T07:16:57.776+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:16:57.910+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:16:57.929+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform_dim_dates.py", line 5, in transform_dim_dates
    warehouse_operator = PostgresOperator('postgres_warehouse')
NameError: name 'PostgresOperator' is not defined
[2024-10-26T07:16:58.030+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=e_commerce_dw_etl, task_id=transform_dim_dates, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20241026T071656, end_date=20241026T071658
[2024-10-26T07:16:58.068+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task transform_dim_dates (name 'PostgresOperator' is not defined; 249)
[2024-10-26T07:16:58.101+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-26T07:16:58.144+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
