[2024-10-26T07:57:42.825+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:57:42.860+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_fact_orders manual__2024-10-26T07:54:35.648807+00:00 [queued]>
[2024-10-26T07:57:42.871+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_fact_orders manual__2024-10-26T07:54:35.648807+00:00 [queued]>
[2024-10-26T07:57:42.872+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-26T07:57:42.890+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_fact_orders> on 2024-10-26 07:54:35.648807+00:00
[2024-10-26T07:57:42.896+0000] {standard_task_runner.py:63} INFO - Started process 1263 to run task
[2024-10-26T07:57:42.900+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform_fact_orders', 'manual__2024-10-26T07:54:35.648807+00:00', '--job-id', '714', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmphd8j6j30']
[2024-10-26T07:57:42.902+0000] {standard_task_runner.py:91} INFO - Job 714: Subtask transform_fact_orders
[2024-10-26T07:57:42.955+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform_fact_orders manual__2024-10-26T07:54:35.648807+00:00 [running]> on host eed3011aebc3
[2024-10-26T07:57:43.053+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T07:54:35.648807+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T07:54:35.648807+00:00'
[2024-10-26T07:57:43.054+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:57:43.076+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-10-26T07:57:43.095+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-10-26T07:57:43.947+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-10-26T07:57:43.960+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-10-26T07:57:44.850+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-10-26T07:57:44.862+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-10-26T07:57:45.322+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-10-26T07:57:45.333+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-10-26T07:57:46.141+0000] {logging_mixin.py:188} INFO - Các cột trong DataFrame sau khi merge:
[2024-10-26T07:57:46.142+0000] {logging_mixin.py:188} INFO - Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'customer_zip_code_prefix'],
      dtype='object')
[2024-10-26T07:57:46.527+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-10-26T07:57:58.858+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào fact_orders
[2024-10-26T07:57:58.927+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-26T07:57:58.928+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:57:58.941+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform_fact_orders, run_id=manual__2024-10-26T07:54:35.648807+00:00, execution_date=20241026T075435, start_date=20241026T075742, end_date=20241026T075758
[2024-10-26T07:57:59.000+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T07:57:59.021+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T07:57:59.025+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
