[2024-10-17T04:01:20.992+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-17T04:01:21.026+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T03:54:41.269906+00:00 [queued]>
[2024-10-17T04:01:21.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T03:54:41.269906+00:00 [queued]>
[2024-10-17T04:01:21.039+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-10-17T04:01:21.056+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_to_staging> on 2024-10-17 03:54:41.269906+00:00
[2024-10-17T04:01:21.067+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1082) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-17T04:01:21.066+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'transform_and_load_to_staging', 'extract_and_load_to_staging', 'manual__2024-10-17T03:54:41.269906+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/extract_data.py', '--cfg-path', '/tmp/tmp314rw746']
[2024-10-17T04:01:21.068+0000] {standard_task_runner.py:63} INFO - Started process 1083 to run task
[2024-10-17T04:01:21.069+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask extract_and_load_to_staging
[2024-10-17T04:01:21.279+0000] {task_command.py:426} INFO - Running <TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T03:54:41.269906+00:00 [running]> on host c5c3360080e3
[2024-10-17T04:01:21.368+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transform_and_load_to_staging' AIRFLOW_CTX_TASK_ID='extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T03:54:41.269906+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T03:54:41.269906+00:00'
[2024-10-17T04:01:21.369+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-17T04:01:21.389+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-10-17T04:01:21.397+0000] {mysql_operator.py:13} ERROR - Can't connect to mysql database
[2024-10-17T04:01:21.406+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-10-17T04:01:21.407+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-17T04:01:21.409+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data.py", line 120, in extract_and_load_to_staging
    df = source_operator.get_data_to_pd(f"SELECT * FROM {table}")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/mysql_operator.py", line 15, in get_data_to_pd
    return self.mysqlhook.get_pandas_df(query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 262, in get_pandas_df
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2024-10-17T04:01:21.430+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=transform_and_load_to_staging, task_id=extract_and_load_to_staging, run_id=manual__2024-10-17T03:54:41.269906+00:00, execution_date=20241017T035441, start_date=20241017T040121, end_date=20241017T040121
[2024-10-17T04:01:21.443+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task extract_and_load_to_staging ((2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)"); 1083)
[2024-10-17T04:01:21.485+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-17T04:01:21.642+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T04:01:21.648+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
