[2024-10-17T04:37:05.326+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-17T04:37:05.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T04:35:18.859889+00:00 [queued]>
[2024-10-17T04:37:05.376+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T04:35:18.859889+00:00 [queued]>
[2024-10-17T04:37:05.377+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-17T04:37:05.396+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_to_staging> on 2024-10-17 04:35:18.859889+00:00
[2024-10-17T04:37:05.402+0000] {standard_task_runner.py:63} INFO - Started process 348 to run task
[2024-10-17T04:37:05.405+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'transform_and_load_to_staging', 'extract_and_load_to_staging', 'manual__2024-10-17T04:35:18.859889+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/extract_data.py', '--cfg-path', '/tmp/tmpi026k7dr']
[2024-10-17T04:37:05.407+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask extract_and_load_to_staging
[2024-10-17T04:37:05.462+0000] {task_command.py:426} INFO - Running <TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T04:35:18.859889+00:00 [running]> on host 515130804d75
[2024-10-17T04:37:05.558+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transform_and_load_to_staging' AIRFLOW_CTX_TASK_ID='extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T04:35:18.859889+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T04:35:18.859889+00:00'
[2024-10-17T04:37:05.559+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-17T04:37:05.717+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-10-17T04:37:05.743+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-10-17T04:37:05.762+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-10-17T04:37:05.779+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-17T04:37:05.791+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 123, in extract_and_load_to_staging
    staging_operator.save_data_to_postgres(
  File "/opt/airflow/plugins/postgresql_operator.py", line 17, in save_data_to_postgres
    conn = self.hook.get_uri()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 204, in get_uri
    return self.sqlalchemy_url.render_as_string(hide_password=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 119, in sqlalchemy_url
    conn = self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_staging` isn't defined
[2024-10-17T04:37:05.803+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=transform_and_load_to_staging, task_id=extract_and_load_to_staging, run_id=manual__2024-10-17T04:35:18.859889+00:00, execution_date=20241017T043518, start_date=20241017T043705, end_date=20241017T043705
[2024-10-17T04:37:05.818+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task extract_and_load_to_staging (The conn_id `postgres_staging` isn't defined; 348)
[2024-10-17T04:37:05.861+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-17T04:37:05.885+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T04:37:05.891+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
