[2024-10-17T13:20:28.678+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-17T13:20:28.725+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T13:20:28.241216+00:00 [queued]>
[2024-10-17T13:20:28.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T13:20:28.241216+00:00 [queued]>
[2024-10-17T13:20:28.743+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-17T13:20:28.778+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_to_staging> on 2024-10-17 13:20:28.241216+00:00
[2024-10-17T13:20:28.787+0000] {standard_task_runner.py:63} INFO - Started process 265 to run task
[2024-10-17T13:20:28.801+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'transform_and_load_to_staging', 'extract_and_load_to_staging', 'manual__2024-10-17T13:20:28.241216+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/extract_data.py', '--cfg-path', '/tmp/tmpxue87ai4']
[2024-10-17T13:20:28.807+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask extract_and_load_to_staging
[2024-10-17T13:20:29.004+0000] {task_command.py:426} INFO - Running <TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T13:20:28.241216+00:00 [running]> on host eed3011aebc3
[2024-10-17T13:20:29.119+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transform_and_load_to_staging' AIRFLOW_CTX_TASK_ID='extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T13:20:28.241216+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T13:20:28.241216+00:00'
[2024-10-17T13:20:29.122+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-17T13:20:29.365+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-10-17T13:20:29.404+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-10-17T13:20:29.430+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-10-17T13:20:29.448+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-10-17T13:20:29.550+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-17T13:20:29.551+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidSchemaName: schema "raw" does not exist
LINE 2: CREATE TABLE raw.raw_product_category_name_translation (
                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 123, in extract_and_load_to_staging
    staging_operator.save_data_to_postgres(
  File "/opt/airflow/plugins/postgresql_operator.py", line 19, in save_data_to_postgres
    df.to_sql(table_name, engine, schema=schema, if_exists=if_exists, index=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 2987, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 695, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 1728, in to_sql
    table = self.prep_table(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 1631, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 838, in create
    self._execute_create()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 824, in _execute_create
    self.table.create(bind=self.pd_sql.connectable)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 962, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3238, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 899, in visit_table
    self.connection.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) schema "raw" does not exist
LINE 2: CREATE TABLE raw.raw_product_category_name_translation (
                     ^

[SQL: 
CREATE TABLE raw.raw_product_category_name_translation (
	product_category_name TEXT, 
	product_category_name_english TEXT
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-10-17T13:20:29.583+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=transform_and_load_to_staging, task_id=extract_and_load_to_staging, run_id=manual__2024-10-17T13:20:28.241216+00:00, execution_date=20241017T132028, start_date=20241017T132028, end_date=20241017T132029
[2024-10-17T13:20:29.604+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task extract_and_load_to_staging ((psycopg2.errors.InvalidSchemaName) schema "raw" does not exist
LINE 2: CREATE TABLE raw.raw_product_category_name_translation (
                     ^

[SQL: 
CREATE TABLE raw.raw_product_category_name_translation (
	product_category_name TEXT, 
	product_category_name_english TEXT
)

]
(Background on this error at: https://sqlalche.me/e/14/f405); 265)
[2024-10-17T13:20:29.654+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-17T13:20:29.681+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T13:20:29.690+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
