[2024-10-17T04:32:15.482+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-17T04:32:15.523+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T04:31:12.326831+00:00 [queued]>
[2024-10-17T04:32:15.538+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T04:31:12.326831+00:00 [queued]>
[2024-10-17T04:32:15.538+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-17T04:32:15.561+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_to_staging> on 2024-10-17 04:31:12.326831+00:00
[2024-10-17T04:32:15.567+0000] {standard_task_runner.py:63} INFO - Started process 240 to run task
[2024-10-17T04:32:15.571+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'transform_and_load_to_staging', 'extract_and_load_to_staging', 'manual__2024-10-17T04:31:12.326831+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/extract_data.py', '--cfg-path', '/tmp/tmpacje8p_8']
[2024-10-17T04:32:15.573+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extract_and_load_to_staging
[2024-10-17T04:32:15.631+0000] {task_command.py:426} INFO - Running <TaskInstance: transform_and_load_to_staging.extract_and_load_to_staging manual__2024-10-17T04:31:12.326831+00:00 [running]> on host 515130804d75
[2024-10-17T04:32:15.726+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transform_and_load_to_staging' AIRFLOW_CTX_TASK_ID='extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T04:31:12.326831+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T04:31:12.326831+00:00'
[2024-10-17T04:32:15.728+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-17T04:32:15.892+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-10-17T04:32:15.908+0000] {mysql_operator.py:13} ERROR - Can't connect to mysql database
[2024-10-17T04:32:15.915+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-10-17T04:32:15.917+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-17T04:32:15.918+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 120, in extract_and_load_to_staging
    df = source_operator.get_data_to_pd(f"SELECT * FROM {table}")
  File "/opt/airflow/plugins/mysql_operator.py", line 15, in get_data_to_pd
    return self.mysqlhook.get_pandas_df(query)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 262, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2024-10-17T04:32:15.935+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=transform_and_load_to_staging, task_id=extract_and_load_to_staging, run_id=manual__2024-10-17T04:31:12.326831+00:00, execution_date=20241017T043112, start_date=20241017T043215, end_date=20241017T043215
[2024-10-17T04:32:15.950+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task extract_and_load_to_staging ((2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)"); 240)
[2024-10-17T04:32:15.985+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-17T04:32:16.008+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T04:32:16.016+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
