[2024-10-17T13:36:18.357+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-17T13:36:18.391+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_and_load_to_staging.transform_and_load_to_staging manual__2024-10-17T13:20:28.241216+00:00 [queued]>
[2024-10-17T13:36:18.401+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_and_load_to_staging.transform_and_load_to_staging manual__2024-10-17T13:20:28.241216+00:00 [queued]>
[2024-10-17T13:36:18.402+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-17T13:36:18.429+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_and_load_to_staging> on 2024-10-17 13:20:28.241216+00:00
[2024-10-17T13:36:18.434+0000] {standard_task_runner.py:63} INFO - Started process 623 to run task
[2024-10-17T13:36:18.437+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'transform_and_load_to_staging', 'transform_and_load_to_staging', 'manual__2024-10-17T13:20:28.241216+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/extract_data.py', '--cfg-path', '/tmp/tmp67lefj2x']
[2024-10-17T13:36:18.440+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask transform_and_load_to_staging
[2024-10-17T13:36:18.493+0000] {task_command.py:426} INFO - Running <TaskInstance: transform_and_load_to_staging.transform_and_load_to_staging manual__2024-10-17T13:20:28.241216+00:00 [running]> on host eed3011aebc3
[2024-10-17T13:36:18.600+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transform_and_load_to_staging' AIRFLOW_CTX_TASK_ID='transform_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T13:20:28.241216+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T13:20:28.241216+00:00'
[2024-10-17T13:36:18.602+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-17T13:36:18.786+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-17T13:36:18.797+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 149, in transform_and_load_to_staging
    df = staging_operator.get_data_to_pd(f"SELECT * FROM public.public_{table}")
  File "/opt/airflow/plugins/postgresql_operator.py", line 14, in get_data_to_pd
    return self.hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 262, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_staging` isn't defined
[2024-10-17T13:36:18.815+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=transform_and_load_to_staging, task_id=transform_and_load_to_staging, run_id=manual__2024-10-17T13:20:28.241216+00:00, execution_date=20241017T132028, start_date=20241017T133618, end_date=20241017T133618
[2024-10-17T13:36:18.841+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task transform_and_load_to_staging (The conn_id `postgres_staging` isn't defined; 623)
[2024-10-17T13:36:18.892+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-17T13:36:18.912+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T13:36:18.926+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
