[2024-10-26T07:17:02.129+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:17:02.313+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_dim_payments scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-10-26T07:17:02.354+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_dim_payments scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-10-26T07:17:02.359+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-26T07:17:02.423+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_dim_payments> on 2024-01-05 00:00:00+00:00
[2024-10-26T07:17:02.450+0000] {standard_task_runner.py:63} INFO - Started process 323 to run task
[2024-10-26T07:17:02.466+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform_dim_payments', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmp7kq3j47b']
[2024-10-26T07:17:02.478+0000] {standard_task_runner.py:91} INFO - Job 102: Subtask transform_dim_payments
[2024-10-26T07:17:02.678+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform_dim_payments scheduled__2024-01-05T00:00:00+00:00 [running]> on host eed3011aebc3
[2024-10-26T07:17:03.088+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform_dim_payments' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-10-26T07:17:03.093+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:17:03.164+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:17:03.199+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform_dim_payments.py", line 8, in transform_dim_payments
    df = staging_operator.get_data_to_pd("SELECT * FROM staging.stg_payments")
  File "/opt/airflow/plugins/postgresql_operator.py", line 14, in get_data_to_pd
    return self.hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 262, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_staging` isn't defined
[2024-10-26T07:17:03.239+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=e_commerce_dw_etl, task_id=transform_dim_payments, run_id=scheduled__2024-01-05T00:00:00+00:00, execution_date=20240105T000000, start_date=20241026T071702, end_date=20241026T071703
[2024-10-26T07:17:03.280+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 102 for task transform_dim_payments (The conn_id `postgres_staging` isn't defined; 323)
[2024-10-26T07:17:03.312+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-26T07:17:03.340+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
