[2024-10-26T07:28:09.189+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:28:09.240+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_dim_dates manual__2024-10-26T07:28:08.065667+00:00 [queued]>
[2024-10-26T07:28:09.256+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform_dim_dates manual__2024-10-26T07:28:08.065667+00:00 [queued]>
[2024-10-26T07:28:09.257+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-26T07:28:09.307+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_dim_dates> on 2024-10-26 07:28:08.065667+00:00
[2024-10-26T07:28:09.318+0000] {standard_task_runner.py:63} INFO - Started process 1537 to run task
[2024-10-26T07:28:09.323+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform_dim_dates', 'manual__2024-10-26T07:28:08.065667+00:00', '--job-id', '517', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpxnwsmzt1']
[2024-10-26T07:28:09.327+0000] {standard_task_runner.py:91} INFO - Job 517: Subtask transform_dim_dates
[2024-10-26T07:28:09.413+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform_dim_dates manual__2024-10-26T07:28:08.065667+00:00 [running]> on host eed3011aebc3
[2024-10-26T07:28:09.558+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform_dim_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T07:28:08.065667+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T07:28:08.065667+00:00'
[2024-10-26T07:28:09.560+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:28:09.578+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:28:09.580+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform_dim_dates.py", line 5, in transform_dim_dates
    warehouse_operator = PostgresOperator('postgres_warehouse')
NameError: name 'PostgresOperator' is not defined
[2024-10-26T07:28:09.598+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=e_commerce_dw_etl, task_id=transform_dim_dates, run_id=manual__2024-10-26T07:28:08.065667+00:00, execution_date=20241026T072808, start_date=20241026T072809, end_date=20241026T072809
[2024-10-26T07:28:09.621+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 517 for task transform_dim_dates (name 'PostgresOperator' is not defined; 1537)
[2024-10-26T07:28:09.658+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-26T07:28:09.691+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T07:28:09.695+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
